site_name: FurryBank Docs

repo_url: https://github.com/YijunStudio/furrybank-docs
repo_name: YijunStudio/furrybank-docs


theme:
  name: material
  palette:
    scheme: default
    primary: white
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime

nav:
  - Welcome: index.md
  - Design: 
    - Database: design/database.md
    - Visual: design/visual.md
  - MkDocs: MkDocs.md